/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.GridBagConstraints;

/**
 *
 * @author kimir
 */
public class registerframe extends javax.swing.JFrame {

    /**
     * Creates new form registerframe
     */
    public registerframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        // Code Panel (2/3 of the frame)
        codePanel = new javax.swing.JPanel();
        codePanel.setBackground(new java.awt.Color(153, 204, 0));
        codePanel.setLayout(new java.awt.GridBagLayout());

        commandsPanel = new javax.swing.JPanel();
        commandsPanel.setBackground(new java.awt.Color(204, 204, 255));
        commandsPanel.setName("nameeee"); 

        GridBagConstraints gbcCommandsPanel = new GridBagConstraints();
        gbcCommandsPanel.fill = GridBagConstraints.BOTH;
        gbcCommandsPanel.weightx = 1.0;
        gbcCommandsPanel.weighty = 0.1;
        codePanel.add(commandsPanel, gbcCommandsPanel);

        code_editor = new javax.swing.JTextArea();
        codeEditorScrollPane = new javax.swing.JScrollPane(code_editor);
        
        GridBagConstraints gbcCodeEditor = new GridBagConstraints();
        gbcCodeEditor.gridx = 0;
        gbcCodeEditor.gridy = 1;
        gbcCodeEditor.gridheight = 9;
        gbcCodeEditor.fill = GridBagConstraints.BOTH;
        gbcCodeEditor.weightx = 1.0;
        gbcCodeEditor.weighty = 0.9;
        codePanel.add(codeEditorScrollPane, gbcCodeEditor);

        GridBagConstraints gbcCodePanel = new GridBagConstraints();
        gbcCodePanel.gridwidth = GridBagConstraints.RELATIVE;
        gbcCodePanel.gridheight = GridBagConstraints.RELATIVE;
        gbcCodePanel.fill = GridBagConstraints.BOTH;
        gbcCodePanel.anchor = GridBagConstraints.WEST;
        gbcCodePanel.weightx = 0.67;
        gbcCodePanel.weighty = 1.0;
        getContentPane().add(codePanel, gbcCodePanel);

        // Info Panel (1/3 of the frame)
        infoPanel = new javax.swing.JPanel();
        infoPanel.setBackground(new java.awt.Color(204, 255, 204));
        infoPanel.setLayout(new java.awt.GridBagLayout());

        akkumulatorPanel = new javax.swing.JPanel();
        akkumulatorPanel.setBackground(new java.awt.Color(255, 204, 102));
        akkumulatorLabel = new javax.swing.JLabel("Akkumulator:");

        GridBagConstraints gbcAkkumulatorPanel = new GridBagConstraints();
        gbcAkkumulatorPanel.gridx = 0;
        gbcAkkumulatorPanel.gridy = 0;
        gbcAkkumulatorPanel.fill = GridBagConstraints.BOTH;
        gbcAkkumulatorPanel.weightx = 1.0;
        gbcAkkumulatorPanel.weighty = 0.1;
        infoPanel.add(akkumulatorPanel, gbcAkkumulatorPanel);

        GridBagConstraints gbcAkkumulatorLabel = new GridBagConstraints();
        gbcAkkumulatorLabel.gridx = 0;
        gbcAkkumulatorLabel.gridy = 1;
        gbcAkkumulatorLabel.fill = GridBagConstraints.BOTH;
        infoPanel.add(akkumulatorLabel, gbcAkkumulatorLabel);

        befehlsregisterPanel = new javax.swing.JPanel();
        befehlsregisterPanel.setBackground(new java.awt.Color(0, 51, 204));
        BefehlsregisterLabel = new javax.swing.JLabel("Befehlsregister");

        GridBagConstraints gbcBefehlsregisterPanel = new GridBagConstraints();
        gbcBefehlsregisterPanel.gridx = 0;
        gbcBefehlsregisterPanel.gridy = 2;
        gbcBefehlsregisterPanel.fill = GridBagConstraints.BOTH;
        gbcBefehlsregisterPanel.weightx = 1.0;
        gbcBefehlsregisterPanel.weighty = 0.1;
        infoPanel.add(befehlsregisterPanel, gbcBefehlsregisterPanel);

        GridBagConstraints gbcBefehlsregisterLabel = new GridBagConstraints();
        gbcBefehlsregisterLabel.gridx = 0;
        gbcBefehlsregisterLabel.gridy = 3;
        gbcBefehlsregisterLabel.fill = GridBagConstraints.BOTH;
        infoPanel.add(BefehlsregisterLabel, gbcBefehlsregisterLabel);

        CellsPanel = new javax.swing.JPanel();
        CellsPanel.setBackground(new java.awt.Color(255, 153, 153));

        GridBagConstraints gbcCellsPanel = new GridBagConstraints();
        gbcCellsPanel.gridx = 0;
        gbcCellsPanel.gridy = 4;
        gbcCellsPanel.gridheight = 8;
        gbcCellsPanel.fill = GridBagConstraints.BOTH;
        gbcCellsPanel.anchor = GridBagConstraints.SOUTH;
        gbcCellsPanel.weightx = 1.0;
        gbcCellsPanel.weighty = 0.8;
        infoPanel.add(CellsPanel, gbcCellsPanel);

        GridBagConstraints gbcInfoPanel = new GridBagConstraints();
        gbcInfoPanel.gridwidth = GridBagConstraints.RELATIVE;
        gbcInfoPanel.gridheight = GridBagConstraints.RELATIVE;
        gbcInfoPanel.fill = GridBagConstraints.BOTH;
        gbcInfoPanel.anchor = GridBagConstraints.EAST;
        gbcInfoPanel.weightx = 0.33;
        gbcInfoPanel.weighty = 1.0;
        getContentPane().add(infoPanel, gbcInfoPanel);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BefehlsregisterLabel;
    private javax.swing.JPanel CellsPanel;
    private javax.swing.JLabel akkumulatorLabel;
    private javax.swing.JPanel akkumulatorPanel;
    private javax.swing.JPanel befehlsregisterPanel;
    private javax.swing.JScrollPane codeEditorScrollPane;
    private javax.swing.JPanel codePanel;
    private javax.swing.JTextArea code_editor;
    private javax.swing.JPanel commandsPanel;
    private javax.swing.JPanel infoPanel;
    // End of variables declaration                   
}
